name: japanese_date_converter
description: A Flutter package to convert DateTime objects to Japanese era (Wareki) date strings, supporting eras from Meiji onwards.
version: 1.0.1
homepage: https://github.com/tsubok547-droid/japanese_date_converter
repository: https://github.com/tsubok547-droid/japanese_date_converter.git

environment:
  sdk: '>=3.8.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: